import Joi from "joi";

export const createUmkmSchema = Joi.object({
  kategori_id: Joi.number().integer().required(),
  nama: Joi.string().max(255).required(),
  slug: Joi.string().max(255).allow(null, "").optional(),
  deskripsi: Joi.string().allow(null, "").optional(),
  pemilik: Joi.string().max(150).allow(null, "").optional(),
  alamat: Joi.string().max(500).allow(null, "").optional(),
  dusun: Joi.string().max(150).allow(null, "").optional(),
  rt: Joi.string().max(50).allow(null, "").optional(),
  rw: Joi.string().max(50).allow(null, "").optional(),
  kecamatan: Joi.string().max(150).allow(null, "").optional(),
  kota: Joi.string().max(150).allow(null, "").optional(),
  provinsi: Joi.string().max(150).allow(null, "").optional(),
  kode_pos: Joi.string().max(20).allow(null, "").optional(),
  telepon: Joi.string().max(50).allow(null, "").optional(),
  whatsapp: Joi.string().max(50).allow(null, "").optional(),
  email: Joi.string().email().allow(null, "").optional(),
  website: Joi.string().uri().allow(null, "").optional(),
  sosial_facebook: Joi.string().allow(null, "").optional(),
  sosial_instagram: Joi.string().allow(null, "").optional(),
  sosial_tiktok: Joi.string().allow(null, "").optional(),
  jenis_usaha: Joi.string().max(150).allow(null, "").optional(),
  status_usaha: Joi.string().max(50).allow(null, "").optional(),
  omset_per_bulan: Joi.number().precision(2).allow(null).optional(),
  skala_usaha: Joi.string().max(50).allow(null, "").optional(),
  jumlah_karyawan: Joi.number().integer().allow(null).optional(),
  logo_url: Joi.string().max(500).allow(null, "").optional(),
  foto_galeri: Joi.any().optional(), // accept JSON string/array
});

export const updateUmkmSchema = Joi.object({
  kategori_id: Joi.number().integer().optional(),
  nama: Joi.string().max(255).optional(),
  slug: Joi.string().max(255).allow(null, "").optional(),
  deskripsi: Joi.string().allow(null, "").optional(),
  pemilik: Joi.string().max(150).allow(null, "").optional(),
  alamat: Joi.string().max(500).allow(null, "").optional(),
  dusun: Joi.string().max(150).allow(null, "").optional(),
  rt: Joi.string().max(50).allow(null, "").optional(),
  rw: Joi.string().max(50).allow(null, "").optional(),
  kecamatan: Joi.string().max(150).allow(null, "").optional(),
  kota: Joi.string().max(150).allow(null, "").optional(),
  provinsi: Joi.string().max(150).allow(null, "").optional(),
  kode_pos: Joi.string().max(20).allow(null, "").optional(),
  telepon: Joi.string().max(50).allow(null, "").optional(),
  whatsapp: Joi.string().max(50).allow(null, "").optional(),
  email: Joi.string().email().allow(null, "").optional(),
  website: Joi.string().uri().allow(null, "").optional(),
  sosial_facebook: Joi.string().allow(null, "").optional(),
  sosial_instagram: Joi.string().allow(null, "").optional(),
  sosial_tiktok: Joi.string().allow(null, "").optional(),
  jenis_usaha: Joi.string().max(150).allow(null, "").optional(),
  status_usaha: Joi.string().max(50).allow(null, "").optional(),
  omset_per_bulan: Joi.number().precision(2).allow(null).optional(),
  skala_usaha: Joi.string().max(50).allow(null, "").optional(),
  jumlah_karyawan: Joi.number().integer().allow(null).optional(),
  logo_url: Joi.string().max(500).allow(null, "").optional(),
  foto_galeri: Joi.any().optional(),
});
